name: wearos_curved_scrollbar
description: "A simple widget that can display a wear OS style curved track."
version: 0.0.2
homepage: https://github.com/cotw-fabier/wearos_curved_scrollbar
repository: https://github.com/cotw-fabier/wearos_curved_scrollbar

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



# Pure dart single widget file with no dependencies. it should work on all platforms though only tested for Android Wear.
# Add platforms section here
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: